---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      community.general.lxd_container:
        name: edge-1
        type: virtual-machine
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases/
          protocol: simplestreams
          alias: "24.04"
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600