---
- name: Install statime
  hosts: edge_servers
  become: true

  vars:
    # The statime version used, the latest version can be found at
    # https://github.com/pendulum-project/statime/releases/
    statime:
      version: "0.3.0"
      url: https://github.com/pendulum-project/statime/releases/download/v0.3.0/statime_0.3.0-1_amd64.deb
      checksum: sha256:3f6bcc0b1dfa21e16b595b190a20dd0e62f5c342aea74d13216620b6f932d5a4
    # The ntpd-rs version used, the latest version can be found at
    # https://github.com/pendulum-project/ntpd-rs/releases/
    ntpd_rs:
      version: "1.5.0"
      url: https://github.com/pendulum-project/ntpd-rs/releases/download/v1.5.0/ntpd-rs_1.5.0-1_amd64.deb
      checksum: sha256:dbbfad4d0395868a369a37cb394f3c8b164c73c9aed6f8b004d58e18c6e1d477

  tasks:
    - ansible.builtin.include_role:
        name: statime
    - ansible.builtin.include_role:
        name: ntpd-rs
