- name: Check current version
  ansible.builtin.shell: 'command -v statime > /dev/null && (statime --version 2>&1 | cut -d" " -f2) || echo "0.0.0"'
  changed_when: false
  register: statime_current_version

- name: Compare versions
  ansible.builtin.set_fact:
    statime_needs_update: "{{ statime_current_version.stdout | trim != statime.version }}"
  changed_when: statime_needs_update | bool

- name: Download and setup new version
  when: statime_needs_update | bool
  block:
    - name: Create Download Directory
      ansible.builtin.tempfile:
        state: directory
      register: download_dir

    - name: Download
      ansible.builtin.get_url:
        url: "{{ statime.url }}"
        dest: "{{ download_dir.path }}"
        mode: "0644"
        checksum: "{{ statime.checksum }}"
      register: statime_deb

    - name: Install
      ansible.builtin.apt:
        deb: "{{ statime_deb.dest }}"
      notify:
        - Restart statime

    - name: Remove download
      ansible.builtin.file:
        state: absent
        path: "{{ download_dir.path }}"

  # End of download and setup

- name: Configure
  ansible.builtin.template:
    src: templates/statime.toml.j2
    dest: /etc/statime/statime.toml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart statime

- name: Enable service
  ansible.builtin.systemd_service:
    enabled: true
    name: statime

- name: Enable metrics service
  ansible.builtin.systemd_service:
    enabled: true
    name: statime-metrics-exporter
